[build]
target = "x86_64-space_invaders.json"

[unstable]
build-std = ["core", "alloc"]

[target.x86_64-unknown-none]
runner = "qemu-system-x86_64 -drive format=raw,file=${workspace_root}/target/x86_64-unknown-none/debug/kernel"

rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-Z", "bindeps"
]

[env]
QEMU_AUDIO_DRV = "none"
